version: '3.8'

services:
  app-service:
    build: ./app-service
    restart: on-failure
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - db-service
      - cache-service
    environment:
      - APP_PORT=${APP_PORT}
      - APP_DATABASE_URL=${APP_DATABASE_URL}
      - SCHEDULER_DATABASE_URL=${SCHEDULER_DATABASE_URL}
      - CACHE_URL=${CACHE_URL}
      - PUBLIC_VAPID_KEY=${PUBLIC_VAPID_KEY}
      - PRIVATE_VAPID_KEY=${PRIVATE_VAPID_KEY}

  cache-service:
    image: redis:7.2.5
    restart: on-failure
    ports:
      - "${CACHE_PORT}:${CACHE_PORT}"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]

  db-service:
    image: mongo:7.0
    restart: on-failure
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - db-data:/data/db

  ui-service:
    build: ./ui-service
    restart: on-failure
    ports:
      - "${UI_PORT}:80"
    depends_on:
      - app-service
    environment:
      - REACT_APP_API_URL=http://app-service:${APP_PORT}
      - REACT_APP_PUBLIC_URL=http://localhost:${UI_PORT}
      - REACT_APP_PUBLIC_VAPID_KEY=${PUBLIC_VAPID_KEY}

volumes:
  db-data:
