version: '3.8'

services:
  nginx-proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app-service
      - ui-service
    networks:
      - app-network

  app-service:
    build: ./app-service
    restart: on-failure
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - db-service
      - cache-service
    environment:
      - APP_PORT=${APP_PORT}
      - APP_DATABASE_URL=${APP_DATABASE_URL}
      - SCHEDULER_DATABASE_URL=${SCHEDULER_DATABASE_URL}
      - CACHE_URL=${CACHE_URL}
      - PUBLIC_VAPID_KEY=${PUBLIC_VAPID_KEY}
      - PRIVATE_VAPID_KEY=${PRIVATE_VAPID_KEY}
    networks:
      - app-network

  cache-service:
    image: redis:7.2.5
    restart: on-failure
    ports:
      - "${CACHE_PORT}:${CACHE_PORT}"
    command: ["redis-server", "--requirepass", "${CACHE_PASSWORD}"]
    networks:
      - app-network

  db-service:
    image: mongo:7.0
    restart: on-failure
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - db-data:/data/db
    networks:
      - app-network

  ui-service:
    build: 
      context: ./ui-service
      args:
        REACT_APP_PUBLIC_VAPID_KEY: ${PUBLIC_VAPID_KEY}
    restart: on-failure
    ports:
      - "${UI_PORT}:80"
    depends_on:
      - app-service
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
